### ISSUE TITLE
Release-specific meta issues

### ISSUE THREAD

**Issue by fxthomas** [airsonic/airsonic#1436]
Hey everyone,

I'd like to create release-specific meta issues on GitHub, so that we can discuss what goes into which release (and put the relevant issues/PRs in milestones). Each issue should have a checklist of things/issues to add to the relevant release.

Specifically, I'd like to:
- [x] Create new meta issues for 10.6 and 11.0 as a starting point
- [x] Pin meta issues so that they appear at the top of the issues list on GitHub
- [x] Create a post on Reddit that explains this and links to the most recent issues

Anybody against it / have other ideas?

**Comment by muff1nman** [comment]
> Create new meta issues for 10.6 and 11.0 as a starting point

So this would be for capturing discussion around the milestone?

>  Pin meta issues so that they appear at the top of the issues list on GitHub

Fine by me.

> Create a post on Reddit that explains this and links to the most recent issues

Also fine by me.

In general - sounds good if someone wants to put the work into it.

One thing to keep in mind - just because someone thinks an issue should get addressed in a release, doesn't mean that someone is going to do it. That partly explains why the current milestone tracking is very light.

**Comment by fxthomas** [comment]
> Just because someone thinks an issue should get addressed in a release, doesn't mean that someone is going to do it.

That's a good point. At least the information about what's planned would be out in the open, and I think that could be better for the project!

**Comment by fxthomas** [comment]
Meta issue template:

```
This issue is a meta issue for discussing the Airsonic 10.6.0 release. I'll keep this up-to-date as we add more information to the discussion.

This won't change how small PRs and issues are merged, but with this I hope we can be a little more open about how the releases are done. These meta issues were discussed in #1436.

Things to do:

- [ ] Important features / fixes (https://github.com/airsonic/airsonic/milestone/6)
  - [ ] _To be determined_
- [ ] Prepare release
  - [ ] Follow the [release documentation](https://github.com/airsonic/airsonic/blob/master/contrib/release.md)
- [ ] Publish release
  - [ ] Publish release on GitHub
  - [ ] Push release on Docker Hub
  - [ ] Write post on Reddit
- [ ] Post-release
  - [ ] Write meta issue for next release
```

**Comment by fxthomas** [comment]
Closing this since it has been implemented.
