### ISSUE TITLE
Libresonic 6.2 Release Plan

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#153]
<a href="https://github.com/EugeneKay"><img src="https://avatars0.githubusercontent.com/u/528798?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EugeneKay](https://github.com/EugeneKay)**
_Sunday Nov 27, 2016 at 22:30 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/153_

----

This will be the Omnibus Release Plan for Libresonic 6.2. This is an information-only Issue; please limit discussions to IRC or other Issues. This will be a development release, meaning that there will be a lot of breakage in the develop branch before it is stable. The main goals for this release are:

1. Reduce the project scope by removing legacy features that are unmaintained, poorly-written, or a bad idea.
    - [X] Remove UPnP. This technology is a bad idea.
    - [X] Remove vestigal licensing code(#77)
    - [X] Remove the Chat feature. Please migrate to the chat platform of your choice; this is not Libresonic's job.
    - [X] Remove remote-access service (yourname.libresonic.org), this service will not be provided. Using your own domain is recommended.
    - [X] ~~Deprecate Casting. A maintainer is welcomed to port this feature to the new media-router implementation, or it will be removed in a future release. (#130)~~ Updated in #195 
    - [ ] ~~Deprecate Sonos and DLNA. These features are untested and a maintainer is welcome to bring them up-to-date, or they will be removed in a future release.~~ Interest has been expressed in keeping these features, so delaying decision until 6.3
2. Bring the codebase up to modern standards and libraries.
    - [X] Update to a newer version of Spring(#80)
    - [X] Replace subsonic-booter with Spring Boot(#142)
3. Improve existing functionality
    - [ ] ~~Automatically locate transcoder binaries(ffmpeg)~~ Delayed until 6.3 due to issues, see #174 
4. Implement oft-requested features as possible.
    - [X] Demo site (#116)
    - [X] External database support(#62)
