### ISSUE TITLE
Broken pages and forms

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#245]
<a href="https://github.com/fxthomas"><img src="https://avatars0.githubusercontent.com/u/613594?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fxthomas](https://github.com/fxthomas)**
_Thursday Feb 09, 2017 at 22:49 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/244_

----

A few pages are broken and need fixing :

- [x] The form in `db.view` fails because of an unsupported method (#245)
- [x] The shuffle radio form in `more.jsp` fails because of a CSRF failure (#246)
- [x] The "Status" page crashes (#247)
