### ISSUE TITLE
Rebrand to Libresonic

### ISSUE THREAD

**Issue by issuemover631** [airsonic/airsonic#40]
<a href="https://github.com/EugeneKay"><img src="https://avatars0.githubusercontent.com/u/528798?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [EugeneKay](https://github.com/EugeneKay)**
_Tuesday May 03, 2016 at 23:05 GMT_
_Originally opened as https://github.com/Libresonic/libresonic/issues/40_

----

Reference history from #36.

There will be a fork of the upstream Subsonic project, which is no longer open-source for 6.0+. The 5.3 codebase(and previous) are licensed under GPLv3, which is already contained here. This issue exists to track the rebrand effort associated with this fork.

In the short term, we must:
- [x] Secure a suitable domain name, eg libresonic.org
- [x] Update the repository documentation(#39).
- [x] Rebase against "new" git history instead of SVN import(#41)
- [x] String-change usage of "Subsonic" in the application(#42)
- [x] Create a new logo. Input and contribution is welcomed(#43)
- [x] Move to Semantic Versioning and modify updater(#44)

Long-term cleanup goals:
- [x] Rename out of the subsonic Java namespace(#52)
- [x] Change remaining user-facing strings
- [x] [Create a website](https://github.com/Libresonic/libresonic.github.io)
- [ ] ~~Contact maintainers of client libraries to provide a FOSS alternative to the now-closed Subsonic~~
- [x] Provide documentation for installation, usage, etc(#64)

Contributions are welcomed in the form of a Pull Request or separate Issue. Additional ideas are welcomed as a comment, but may be ignored.
